site_name: Python-utils
site_url: https://github.com/chenjiandongx
site_description: Python 实用工具函数
site_author: chenjiandongx

repo_url: https://github.com/chenjiandongx/python-utils
repo_name: 'chenjiandongx/python-utils'

markdown_extensions:
    - toc:
        permalink: ->
    - admonition
    - def_list
    - codehilite

copyright: Copyright &copy; 2018 <a href="https://github.com/chenjiandongx">chenjiandongx</a>.

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  social:
    - type: 'github'
      link: 'https://github.com/chenjiandongx'
plugins:
    - search
